# Generated by Django 5.2.7 on 2025-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjk404", "0004_alter_pagenotfoundentry_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pagenotfoundentry",
            options={
                "ordering": ("-hits",),
                "verbose_name": "redirect",
                "verbose_name_plural": "redirects",
            },
        ),
        migrations.AddField(
            model_name="pagenotfoundentry",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active?"),
        ),
    ]
