# Generated by Django 5.2.7 on 2025-11-24 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cjk404", "0005_alter_pagenotfoundentry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagenotfoundentry",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="Updated",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pagenotfoundentry",
            name="fallback_redirect",
            field=models.BooleanField(
                default=False,
                help_text="This redirect is only matched after all other redirects have failed to match.<br>This allows us to define a general 'catch-all' that is only used as a fallback after more specific redirects have been attempted.",
                verbose_name="Fallback Redirect",
            ),
        ),
        migrations.AlterField(
            model_name="pagenotfoundentry",
            name="hits",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Views"
            ),
        ),
        migrations.AlterField(
            model_name="pagenotfoundentry",
            name="regular_expression",
            field=models.BooleanField(default=False, verbose_name="Regular Expression"),
        ),
    ]
