# Generated by Django 5.2.7 on 2025-11-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cjk404", "0006_pagenotfoundentry_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagenotfoundentry",
            name="updated",
            field=models.DateTimeField(
                auto_now=True,
                blank=True,
                null=True,
                verbose_name="Updated",
            ),
        ),
        migrations.RunSQL(
            sql="UPDATE cjk404_pagenotfoundentry SET updated = NULL;",
            reverse_sql=(
                "UPDATE cjk404_pagenotfoundentry "
                "SET updated = created "
                "WHERE updated IS NULL AND created IS NOT NULL;"
            ),
        ),
    ]
